import { TaskRecord } from '../types';

export const initialSampleTasks: TaskRecord[] = [
  {
    id: 'OCD-2025-001',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-19',
    vendedor: 'Carlos Benítez',
    codigoVendedor: 'VEND-104',
    supervisor: 'Roberto Domínguez',
    ruta: 'Ruta 101 - Morón Centro',
    codigoPDV: 'PDV-4520',
    nombrePDV: 'Autoservicio El Trebol',
    direccionPDV: 'Av. Rivadavia 17820, Morón',
    categoriaTarea: 'Heladera OCD',
    nombreTarea: 'Auditoría Heladera OCD 100% Exclusiva',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'Producto de competencia en equipo de frío exclusivo',
    detalleInvalidacion: 'Se observa una botella de marca ajena en el estante superior izquierdo.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 25,
    puntajeObtenido: 0,
    estadoApelacion: 'EN_REVISION',
    fechaApelacion: '2025-02-20T11:15:00.000Z',
    motivoApelacion: 'El cliente la colocó temporalmente mientras reponía stock. Se retiró inmediatamente y se adjunta foto corregida con el equipo 100% puro.',
    evidenciaApelacionUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=1200&q=80',
    comentariosVendedor: 'Solicito reconsideración de los 25 puntos de ejecución.',
  },
  {
    id: 'OCD-2025-002',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-19',
    vendedor: 'Mariana Gómez',
    codigoVendedor: 'VEND-108',
    supervisor: 'Silvia Menéndez',
    ruta: 'Ruta 102 - Castelar Norte',
    codigoPDV: 'PDV-3912',
    nombrePDV: 'Minimarket Los Pinos',
    direccionPDV: 'Arias 2340, Castelar',
    categoriaTarea: 'Material POP',
    nombreTarea: 'Colocación Afiche Campaña Lanzamiento 2.25L',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'Foto borrosa o con reflejo excesivo',
    detalleInvalidacion: 'No se logra verificar la fecha del afiche ni el código de local por reflejo de luz solar.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 15,
    puntajeObtenido: 0,
    estadoApelacion: 'SIN_APELAR',
    comentariosVendedor: '',
  },
  {
    id: 'OCD-2025-003',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-18',
    vendedor: 'Lucas Pereyra',
    codigoVendedor: 'VEND-112',
    supervisor: 'Roberto Domínguez',
    ruta: 'Ruta 105 - San Justo Comercial',
    codigoPDV: 'PDV-8104',
    nombrePDV: 'Supermercado Don Pepe',
    direccionPDV: 'Dr. I. Arieta 3100, San Justo',
    categoriaTarea: 'Facing / Góndola',
    nombreTarea: 'Facing Primario 4 Caras Gaseosas Línea Sabor',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'Cantidad de caras inferior al estándar acordado',
    detalleInvalidacion: 'Solo se observan 2 caras en lugar de las 4 pactadas.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 20,
    puntajeObtenido: 0,
    estadoApelacion: 'APROBADA',
    fechaApelacion: '2025-02-19T09:40:00.000Z',
    motivoApelacion: 'En la foto general se ve el bloque completo en el pasillo principal con 4 caras.',
    evidenciaApelacionUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80',
    comentariosVendedor: 'Adjunto foto panorámica del pasillo.',
    fechaResolucion: '2025-02-19T16:20:00.000Z',
    supervisorResolutor: 'Roberto Domínguez',
    dictamenResolucion: 'APROBADA',
    comentarioResolucion: 'Verificado en foto panorámica. Se aprueba la apelación y se restituyen los 20 puntos.',
    puntajeAjustado: 20,
  },
  {
    id: 'OCD-2025-004',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-18',
    vendedor: 'Valeria Rossi',
    codigoVendedor: 'VEND-115',
    supervisor: 'Silvia Menéndez',
    ruta: 'Ruta 108 - Ramos Mejía',
    codigoPDV: 'PDV-6120',
    nombrePDV: 'Kiosco Central 24hs',
    direccionPDV: 'Av. de Mayo 450, Ramos Mejía',
    categoriaTarea: 'Control de Precios',
    nombreTarea: 'Relevamiento de Precios Sugeridos Línea Retornable',
    estadoValidacion: 'VALIDADA',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 10,
    puntajeObtenido: 10,
    estadoApelacion: 'SIN_APELAR',
  },
  {
    id: 'OCD-2025-005',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-19',
    vendedor: 'Carlos Benítez',
    codigoVendedor: 'VEND-104',
    supervisor: 'Roberto Domínguez',
    ruta: 'Ruta 101 - Morón Centro',
    codigoPDV: 'PDV-5510',
    nombrePDV: 'Almacén Don Carlos',
    direccionPDV: 'Buen Viaje 920, Morón',
    categoriaTarea: 'Exhibición Especial',
    nombreTarea: 'Isla de Producto en Entrada con Cenefa Promocional',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'No coincide PDV o fachada no reconocible',
    detalleInvalidacion: 'La foto tomada no incluye elemento identificador del cliente ni cartel.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 30,
    puntajeObtenido: 0,
    estadoApelacion: 'SIN_APELAR',
  },
  {
    id: 'OCD-2025-006',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-17',
    vendedor: 'Martín Albarracín',
    codigoVendedor: 'VEND-120',
    supervisor: 'Roberto Domínguez',
    ruta: 'Ruta 101 - Morón Centro',
    codigoPDV: 'PDV-1090',
    nombrePDV: 'Despensa La Familia',
    direccionPDV: 'Mitre 410, Morón',
    categoriaTarea: 'Material POP',
    nombreTarea: 'Colocación de Stopper y Regleta en Góndola',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'Falta material POP obligatorio',
    detalleInvalidacion: 'Solo se observa el stopper; falta la regleta frontal.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 15,
    puntajeObtenido: 0,
    estadoApelacion: 'RECHAZADA',
    fechaApelacion: '2025-02-18T10:00:00.000Z',
    motivoApelacion: 'El cliente no tenía espacio en el fleje para la regleta.',
    evidenciaApelacionUrl: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&w=1200&q=80',
    comentariosVendedor: 'Pido consideración por falta de espacio físico.',
    fechaResolucion: '2025-02-18T17:45:00.000Z',
    supervisorResolutor: 'Roberto Domínguez',
    dictamenResolucion: 'RECHAZADA',
    comentarioResolucion: 'El acuerdo comercial exige regleta. En caso de falta de espacio se debe reubicar en estante contiguo.',
    puntajeAjustado: 0,
  },
  {
    id: 'OCD-2025-007',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-19',
    vendedor: 'Mariana Gómez',
    codigoVendedor: 'VEND-108',
    supervisor: 'Silvia Menéndez',
    ruta: 'Ruta 102 - Castelar Norte',
    codigoPDV: 'PDV-9801',
    nombrePDV: 'Kiosco La Estación',
    direccionPDV: 'Los Incas 2100, Castelar',
    categoriaTarea: 'Heladera OCD',
    nombreTarea: 'Control de Temperatura y Planograma de Heladera',
    estadoValidacion: 'VALIDADA',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 25,
    puntajeObtenido: 25,
    estadoApelacion: 'SIN_APELAR',
  },
  {
    id: 'OCD-2025-008',
    importBatchId: 'batch_inicial_demo',
    importDate: '2025-02-20T08:30:00.000Z',
    fechaTarea: '2025-02-19',
    vendedor: 'Valeria Rossi',
    codigoVendedor: 'VEND-115',
    supervisor: 'Silvia Menéndez',
    ruta: 'Ruta 108 - Ramos Mejía',
    codigoPDV: 'PDV-7740',
    nombrePDV: 'Super Express San Martín',
    direccionPDV: 'San Martín 890, Ramos Mejía',
    categoriaTarea: 'Facing / Góndola',
    nombreTarea: 'Exhibición Puntera de Góndola Galletitas OCD',
    estadoValidacion: 'INVALIDADA',
    motivoInvalidacion: 'Foto tomada fuera del rango o ángulo incorrecto',
    detalleInvalidacion: 'No se puede constatar la totalidad de la puntera.',
    urlFotoOriginal: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80',
    puntajeBase: 20,
    puntajeObtenido: 0,
    estadoApelacion: 'EN_REVISION',
    fechaApelacion: '2025-02-20T14:30:00.000Z',
    motivoApelacion: 'Tomo foto en plano general con vista completa de los 5 estantes de la puntera.',
    evidenciaApelacionUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80',
    comentariosVendedor: 'Adjunto link y foto en alta definición para cotejar.',
  },
];
